### PR TITLE
The topic data update for English, Korean, Japanese and Simplified Chinese(更新英语、韩语、日语和简体中文的专题数据)

### PR DESCRIPTION
**Pull request by mzj21**
The topic data update for English, Korean, Japanese and Simplified Chinese(更新英语、韩语、日语和简体中文的专题数据)

### CODE REVIEW

**Comment by qutrits** [comment]
Can you explain what has changed?

**Comment by mzj21** [comment]
> Can you explain what has changed?

1.All shows selector data for English, Korean, Japanese and Simplified Chinese..
2.The original NotoSans-Regular.ttf font will not actually be used if you do not have it installed. I downloaded from https://fonts.google.com/noto/specimen/Noto+Sans?query=NOTO+SANS the latest font.

**Comment by mzj21** [comment]
image

**Comment by qutrits** [comment]
The font is the Noto Sans CJK version and should not be changed.

**Comment by mzj21** [comment]
> The font is the Noto Sans CJK version and should not be changed.

Left: Current Version(1.135 Noto Sans CJK), Chinese Traditional and blurred font. Right: PR Version(Noto Sans), Simplified Chinese and Clear font.
image

**Comment by qutrits** [comment]
This font is not just for Chinese.
If you change the font, it will break any UI you've built.

**Comment by mzj21** [comment]
> It's not just for Chinese - it's also for Korean and Japanese. If you change the font, it will break any UI you've built.
image
My latest submission fixes this, But now I need to resolve the conflict.

**Comment by mzj21** [comment]
wait, I need to fix things again.

**Comment by mzj21** [comment]
All shows selector data update for English, Korean, Japanese and Simplified Chinese.
Change NotoSans-Regular.ttf, new from https://fonts.google.com/noto/specimen/Noto+Sans?query=NOTO+SANS.
Fixed untidy interface caused by font changes.

**Comment by qutrits** [comment]
Check out the difference in the size of the font files and google what the CJK version is.

**Comment by mzj21** [comment]
> image

CJK version will cause this BUG, I researched for a long time yesterday and found this problem.

**Comment by mzj21** [comment]
These are new PR Version Screenshot.
image
image
image
image

**Comment by qutrits** [comment]
No, I'm just saying that the fontfile shouldn't be changed.

**Comment by mzj21** [comment]
> No, I'm just saying that the fontfile shouldn't be changed.

But this CJK Font will cause simplified Chinese to become traditional Chinese

**Comment by mzj21** [comment]
A more universal font was needed, Not buggy, blurry, unstyled fonts.

**Comment by qutrits** [comment]
Then you'll need to add a font for Chinese, add logic to change the main font to Chinese, and modify all the UI to match the font.

**Comment by iku55** [comment]
Here is a comparison of the settings screen for 1.135 and this PR (left: this pr, right: 1.135).
I can't read that the letters are different.
image
image
image
image

**Comment by mzj21** [comment]
> Here is a comparison of the settings screen for 1.135 and this PR (left: this pr, right: 1.135) in my enviroment. I can't read that the letters are different. image image image image

From the last screenshot you can see that the font is still the CJK version, showing traditional Chinese instead of Simplified Chinese.

**Comment by mzj21** [comment]
You can try uninstalling CJK version font.

**Comment by qutrits** [comment]
Find information about fonts [here](https://github.com/googlefonts/noto-cjk).

**Comment by mzj21** [comment]
I made a video explaining my situation.
https://streamable.com/c2mn8a

**Comment by qutrits** [comment]
If you search for 'settings_always_show_on_top' in the Multilingual.cs file, it is written as '置顶显示' from the beginning. It is the effect of the OS, so try adjusting the OS font.

**Comment by mzj21** [comment]
image
These characters are not simplified or traditional Chinese.
image
image
image
https://en.wiktionary.org/wiki/%E6%89%8D
https://en.wiktionary.org/wiki/%E5%B9%B3
https://en.wiktionary.org/wiki/%E7%BD%AE

**Comment by qutrits** [comment]
So it's not the font file that's bad, it's the wording in Multilingual.cs.

**Comment by iku55** [comment]
I think the problem is probably that Noto Sans CJK KR is used. Also, Noto Sans does not include Japanese, Korean, and Chinese glyphs.
Noto Sans CJK (KR) includes Chinese, Japanese, and Korean glyphs, and seems to prioritize Korean among them.
So use [Noto Sans JP](https://fonts.google.com/noto/specimen/Noto+Sans+JP) for Japanese, 
[Noto Sans KR](https://fonts.google.com/noto/specimen/Noto+Sans+KR) for Korean, and [Noto Sans SC](https://fonts.google.com/noto/specimen/Noto+Sans+SC) for Simplified Chinese.
However, the size may increase.

**Comment by qutrits** [comment]
[NotoSansSC-Regular.zip](https://github.com/ShootMe/FallGuysStats/files/10719831/NotoSansSC-Regular.zip)
I'm trying to PR with this font, but you can check it out on your PC.

**Comment by qutrits** [comment]
[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/10720145/FallGuysStats.zip)
A version with additional fonts for simplified Chinese.

**Comment by mzj21** [comment]
> [FallGuysStats.zip  FallGuysStats.zip ](https://github.com/ShootMe/FallGuysStats/files/10721131/FallGuysStats.zip) A version with additional fonts for simplified Chinese.带有附加简体中文字体的版本。

image
There are no problems in simplified Chinese except for lack of clarity. (My PC Scaling is 150%)
Other languages still look BUG.

**Comment by mzj21** [comment]
I cancelled the submission to change the font and the setting screen, and only keep all shows selector data.

**Comment by qutrits** [comment]
Why did the number of shows decrease in the original data?

**Comment by mzj21** [comment]
I reorganized the data

**Pull request closed without merging**
