### PR TITLE
Optional data reporting to Fallalytics

### PR DESCRIPTION
**Pull request by Hoier**
[Fallalytics](https://fallalytics.com) is a website for displaying information about round distribution in Fall Guys.

With this pull request, I have added the option to enable round info to be sent to Fallalytics after each game.

The trigger for this is happening on [line 1345 in stats.cs](https://github.com/Hoier/FallGuysStats/blob/d2acf35c6867686c9fd144008bdb57c735e78a9c/Views/Stats.cs#L1345).

If the user has enabled the setting for reporting data, information is sent to the Fallalytics API in the following format:
```
POST https://fallalytics.com/api/report

HEADERS:
'Content-Type: application/json'
'Authorization: Bearer + APIKEY'

BODY:
{
   "round":RoundInfo.Name, (String)
   "index":RoundInfo.Round, (Int)
   "show":"RoundInfo.ShowNameId, (String)
   "isfinal":RoundInfo.IsFinal.ToString().ToLower(), (bool),
   "session":RoundInfo.SessionId (String)(*)
}
```
*: SessionId is the ID of the episode from Mediatonic. It is the same for any players in the same game/round/episode. Its needed so we dont store the same round twice, when multiple players in the same game have the reporting enabled.  

I have added it to the RoundInfo Class, and its set in [LogFileWatchers.cs on line 365 -> 367](https://github.com/Hoier/FallGuysStats/blob/d2acf35c6867686c9fd144008bdb57c735e78a9c/Entities/LogFileWatcher.cs#L365) in the same way ShowNameId is set.

A new tile has been added to the settings form to enable/disable the data reporting.

**If the Fallalytics API is unavailable, or sends back an error code, the tracker will keep working as it does today. No breaking changes or online dependencies introduced.**

I have in the past distributed a "Fallalytics build" on the website, which is just a clone of FallGuysStats with the data reporting included.
With this pull request, I hope the fallalytics data collectors can have an easier way of making sure their tracker is up to date, and that the source code is available to anyone who wants to audit. 

**Any feedback, requests or questions are more than welcome!**

### CODE REVIEW

**Comment by qutrits** [comment]
Is the repository for the FALLALYTICS site private? If possible, I'd like to see a public repository so that others can PR to support other languages like Korean or Japanese in addition to English.

And since the information about how many rounds have been played may not be important to the user, it would be nice to get the passing time of each round for example and show the statistics, what do you think?

**Comment by Hoier** [comment]
> @Hoier Is the repository for the FALLALYTICS site private? If possible, I'd like to see a public repository so that others can PR to support other languages like Korean or Japanese in addition to English.

This sounds like a good idea. I willl have to do a clean up job for the site source code, but I will get on that asap.

> And since the information about how many rounds have been played may not be important to the user, it would be nice to get the passing time of each round for example and show the statistics, what do you think?

Are you thinking how long the round takes, and the avarage fishish time + fastest?
I can update the tracker to include this, but It will take a little longer to include in the front-end.

> + If the aforementioned tasks are possible, is it possible to replace it with a way to toggle options without having to enter an API-key?

The API Key is currently optional, and I only included it as an option if the API gets spammed by low MMR players. I could on the server side activate authentication, and only games from players that has revieved a valid API key would be logged.

**Comment by Hoier** [comment]
@qutrits Thank you for the input. I will create a repo for the site later this week, and we can discuss its features there.
How about the pull request? Ok to merge?

**Comment by iku55** [comment]
I think it would be good to add a description of Fallalytics!

**Comment by Hoier** [comment]
@iku55 I didnt want to "advertise" fallalytics in the app, to not be to pushy. @qutrits What do you think? A short text about what the service is, and a link to the websites /about?

**Comment by qutrits** [comment]
@Hoier Can you put a link to your site and an introduction in the fallalytics menu? I'll merge the PR and translate them into 5 languages.

**Pull request merged**
